name: beingwatched
version: "1.0.0"
profile: beingwatched

model-paths: ["models"]

models:
  beingwatched:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
